apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuerHTTP01.name | quote }}
spec:
  acme:
    server: {{ .Values.clusterIssuerHTTP01.acme.server | quote }}
    email: {{ .Values.clusterIssuerHTTP01.acme.email | quote }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuerHTTP01.acme.privateKeySecretRef.name | quote }}
    solvers:
    - http01:
        ingress:
          class: nginx
