apiVersion: v2
name: external-dns
description: A Helm chart for External DNS
type: application
version: 0.1.0
appVersion: "1.16.1"
dependencies:
  - name: external-dns
    version: 1.16.1
    repository: https://kubernetes-sigs.github.io/external-dns 