apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: 0.1.0
appVersion: "1.17.1"
dependencies:
  - name: cert-manager
    version: 1.17.1
    repository: https://charts.jetstack.io 