apiVersion: v2
name: ingress-nginx
description: A Helm chart for ingress-nginx
type: application
version: 0.1.0
appVersion: "1.12.1"
dependencies:
  - name: ingress-nginx
    version: 4.12.1
    repository: https://kubernetes.github.io/ingress-nginx 