apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment2
  namespace: lwsn
  labels:
    app: assignment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment2
  template:
    metadata:
      labels:
        app: assignment2
    spec:
      containers:
        - name: assignment2
          image: 289831833738.dkr.ecr.eu-north-1.amazonaws.com/assignment2/lwsn:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: assignment2-secret
                  key: DATABASE_URL
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          emptyDir: {}
